CREATE TABLE DAILY_POWER(
  DATE TEXT NOT NULL,
  DEVICE_ID INT NOT NULL,
  VOLTAGE REAL NOT NULL,
  CURRENT REAL NOT NULL,
  POWER INT NOT NULL,
  ENERGY INT NOT NULL,
  primary key (DATE, DEVICE_ID)
);
